### PR TITLE
Also install logstash-contrib

### PR DESCRIPTION
**Pull request by K-Phoen**
Will enable the use of community-contributed plugins.

### CODE REVIEW

**Comment by willdurand** [comment]
thanks <3

**Comment by hacfi** [comment]
FYI: If I understand https://github.com/elastic/logstash-contrib#all-new--please-read correctly this has to removed again as soon as you’re using logstash 1.5.

**Comment by willdurand** [comment]
Yes, but we are not using 1.5 right now.

**Comment by hacfi** [comment]
I know...was just meant as a heads up when updating later.

**Pull request merged**
